-- Chunk B: products, orders

CREATE TABLE IF NOT EXISTS products (
  id          CHAR(36)      NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  owner_id    CHAR(36)      NOT NULL,
  category_id BIGINT        NULL,
  name        VARCHAR(255)  NOT NULL,
  slug        VARCHAR(255)  NOT NULL,
  brand       VARCHAR(160)  NULL,
  description TEXT          NULL,
  price       DECIMAL(12,2) NOT NULL,
  mrp         DECIMAL(12,2) NULL,
  stock       INT           NOT NULL DEFAULT 0,
  sku         VARCHAR(120)  NOT NULL UNIQUE,
  status      ENUM('draft','review','live','rejected','archived') NOT NULL DEFAULT 'review',
  images      JSON          NOT NULL,
  rating      DECIMAL(2,1)  NULL,
  review_note TEXT          NULL,
  reviewed_by CHAR(36)      NULL,
  reviewed_at DATETIME(3)   NULL,
  created_at  DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at  DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX idx_products_owner_created (owner_id, created_at DESC),
  INDEX idx_products_status (status),
  INDEX idx_products_category (category_id),
  FULLTEXT INDEX ftx_products_name (name),
  CONSTRAINT fk_products_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id                CHAR(36)      NOT NULL DEFAULT (uuid()) PRIMARY KEY,
  order_no          VARCHAR(64)   NOT NULL UNIQUE,
  client_id         CHAR(36)      NULL,
  product_id        CHAR(36)      NULL,
  product_name      VARCHAR(255)  NOT NULL,
  customer_name     VARCHAR(160)  NOT NULL,
  city              VARCHAR(100)  NOT NULL,
  state             VARCHAR(100)  NULL,
  channel           ENUM('online','field') NOT NULL DEFAULT 'online',
  officer_name      VARCHAR(160)  NULL,
  officer_id        CHAR(36)      NULL,
  customer_phone    VARCHAR(32)   NULL,
  qty               INT           NOT NULL,
  unit_price        DECIMAL(12,2) NOT NULL,
  amount            DECIMAL(12,2) NOT NULL,
  commission_rate   DECIMAL(5,4)  NOT NULL DEFAULT 0.0800,
  commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  status            ENUM('processing','packed','in-transit','delivered','returned','cancelled') NOT NULL DEFAULT 'processing',
  placed_at         DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_orders_client_created (client_id, created_at DESC),
  INDEX idx_orders_status (status),
  INDEX idx_orders_channel (channel),
  INDEX idx_orders_placed_at (placed_at DESC),
  INDEX idx_orders_officer (officer_id, placed_at DESC),
  CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_officer FOREIGN KEY (officer_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
